# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 09:07
from __future__ import unicode_literals

import UnixTimestampField
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=255, unique=True)),
                ('load', models.TextField()),
            ],
            options={
                'db_table': 'jids',
            },
        ),
        migrations.CreateModel(
            name='salt_events',
            fields=[
                ('alter_time', UnixTimestampField.UnixTimestampField(auto_created=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(db_index=True, max_length=255)),
                ('data', models.TextField()),
                ('master_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'salt_events',
            },
        ),
        migrations.CreateModel(
            name='salt_returns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alter_time', UnixTimestampField.UnixTimestampField(auto_created=True, null=True)),
                ('fun', models.CharField(db_index=True, max_length=50)),
                ('jid', models.CharField(db_index=True, max_length=255)),
                ('return_field', models.TextField(db_column='return')),
                ('minion_id', models.CharField(db_index=True, max_length=255)),
                ('success', models.CharField(max_length=10)),
                ('full_ret', models.TextField()),
            ],
            options={
                'db_table': 'salt_returns',
            },
        ),
    ]
