# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 09:14
from __future__ import unicode_literals

import UnixTimestampField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salt_events',
            name='alter_time',
            field=UnixTimestampField.UnixTimestampField(null=True),
        ),
        migrations.AlterField(
            model_name='salt_returns',
            name='alter_time',
            field=UnixTimestampField.UnixTimestampField(null=True),
        ),
    ]
