# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='serverInfo',
            new_name='serverList',
        ),
    ]
