# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0002_auto_20170612_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='datadisk',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='remark',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
