# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0004_auto_20170612_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='datadisk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
