# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0005_auto_20170612_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='alter_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
